openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: API for user registration, authentication, and management
servers:
  - url: http://localhost:3000/api/v1
paths:
  /register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "201":
          description: User registered successfully
  /login:
    post:
      summary: Log in a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: User logged in successfully
  /user:
    get:
      summary: Get user information
      tags:
        - Users
      security:
        - cookieAuth: []
      responses:
        "200":
          description: User information retrieved successfully
